### ISSUE TITLE
Can't create a video

### ISSUE THREAD

**Issue by oren** [noffle/screen-stream#6]
I can't create the video. running `screen-stream > recording.mp4` ends right away and creates empty file called recording.mp4.

`strace -fo output screen-stream > recording.mp4`: http://paste.ubuntu.com/11706378/

`uname -a`: 3.19.0-16-generic #16-Ubuntu SMP
`cat /etc/release`: 15.04

**Comment by hackergrrl** [comment]
Thanks for filing a bug. Do you have `ffmpeg` installed? What version?

**Comment by oren** [comment]
ffmeg was removed from ubuntu's repositories. it's back in 15.04 - http://www.webupd8.org/2014/11/ffmpeg-returns-to-official-ubuntu.html

`apt-get install ffmpeg` solved it. thanks!
